import type { Metadata } from "next";
import { Karantina, Karla } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navigation/NavBar";
import IntroWebsite from "@/components/loader/IntroWebsite";
import LenisProvider from "@/components/LenisProvider";

const karantina = Karantina({
  variable: "--font-karantina",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${karantina.variable} antialiased bg-black`}
      >
        <NavBar />

        <IntroWebsite />
        {children}
      </body>
    </html>
  );
}
