import type { Metadata } from "next";
import { Karantina, Karla, Boldonse, Oswald, Anton } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navigation/NavBar";
import IntroWebsite from "@/components/loader/IntroWebsite";

const karantina = Karantina({
  variable: "--font-karantina",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const boldonse = Boldonse({
  variable: "--font-boldonse",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${karantina.variable} ${boldonse.variable} ${oswald.variable} ${anton.variable} antialiased bg-black`}
      >
        <NavBar />
        <IntroWebsite />
        {children}
      </body>
    </html>
  );
}
